context:
  version: 0.0.1

package:
  name: xeus-ocaml
  version: ${{ version }}

source:
<<<<<<< HEAD
  path: ../
=======
  path: .
>>>>>>> 7545d44095e7bc9b75d60347cc11c84732498351

build:
  number: 2

requirements:
  build:
  - ${{ compiler("cxx") }}
  - cmake
  - ninja
  host:
  - nlohmann_json
  - xeus
  - xeus-lite

tests:
- script:
  - test -f $PREFIX/bin/xocaml.wasm
  - test -f $PREFIX/bin/xocaml.js
about:
  license: BSD-3-Clause
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-javascript
  homepage: https://github.com/davy39/xeus-ocaml
extra:
  recipe-maintainers:
  - Davy39