[project]
name = "xeus-ocaml-wasm-build"
channels = ["conda-forge", "https://repo.prefix.dev/emscripten-forge-dev"]
platforms = ["linux-64","emscripten-wasm32"]

# Environnement pour compiler en WebAssembly avec Emscripten

[feature.wasm-build]
platforms = ["linux-64"]

[feature.wasm-build.dependencies]
emsdk = ">=3.1.46"
cmake = "*"

[feature.wasm-build.tasks]
configure_wasm_build = { cmd = "emsdk update && emsdk install 3.1.73 && emsdk activate 3.1.73", depends-on = [] }


[feature.wasm-host]
platforms = ["emscripten-wasm32"]

# Environnement cible contenant les dépendances d'exécution WASM
[feature.wasm-host.dependencies]
xeus = "*"
xeus-lite = "*"
nlohmann_json ="*"



[feature.wasm-host.tasks]
setup_wasm = { cmd = "pixi run -e wasm-build configure_wasm_build", inputs = ["pixi.lock"] }


# Configure le projet avec emcmake



configure_ocaml_kernel = { cmd = """
bash -c 'source ".pixi/envs/wasm-build/lib/python3.13/site-packages/emsdk/emsdk_env.sh" && \
export EMPACK_PREFIX=../.pixi/envs/wasm-build && \
export PREFIX=../.pixi/envs/default && \
export CMAKE_PREFIX_PATH=$PREFIX && \
export CMAKE_SYSTEM_PREFIX_PATH=$PREFIX && \
mkdir -p build && cd build && \
emcmake cmake \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_PREFIX_PATH=$PREFIX \
-DCMAKE_INSTALL_PREFIX=$PREFIX \
-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON \
..'
""", depends-on = ["setup_wasm"] }


# Construit le kernel
build_ocaml_kernel = { cmd = "make -C build -j", depends-on = ["configure_ocaml_kernel"] }

# Installe le kernel dans le préfixe de l'environnement
install_ocaml_kernel = { cmd = "make -C build install", depends-on = ["build_ocaml_kernel"] }


[feature.jupyter]
platforms = ["linux-64"]

# Environnement pour construire et servir JupyterLite
[feature.jupyter.dependencies]
jupyterlab-language-pack-fr-FR = "*"
jupyterlite-xeus = "==4.2.0"
jupyter_server = "*"
ipywidgets = "*"
jupyterlab = "*"

# Tâches pour la compilation du kernel OCaml en WASM
# Ces tâches s'exécuteront dans l'environnement 'wasm-build'
[feature.jupyter.tasks]

setup_ocaml = { cmd = "pixi run -e default install_ocaml_kernel"}

# Construit l'application JupyterLite
jupyter_build = { cmd = "jupyter lite build --XeusAddon.prefix=.pixi/envs/default", depends-on = ["setup_ocaml"] }

# Sert l'application JupyterLite
jupyter_serve = { cmd = "python -m http.server 8000 --directory _output", depends-on = ["jupyter_build"] }


[environments]
default = { features = ["wasm-host"] }
wasm-build = { features = ["wasm-build"] }
jupyter = { features = ["jupyter"] }