name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  emscripten_wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Build js_of_ocaml kernel
        run: |
          opam install dune js_of_ocaml lwt graphics js_of_ocaml-lwt js_of_ocaml-ppx js_of_ocaml-toplevel base
          opam exec -- dune build --root src/ocaml/ 

      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          build-args: -c https://repo.prefix.dev/emscripten-forge-dev -c conda-forge --target-platform emscripten-wasm32
          recipe-path: recipe/recipe.yaml

      - name: Upload conda package
        run: |
          for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
            echo "Uploading ${pkg}"
            rattler-build upload prefix -c emscripten "${pkg}"
          done