name: CI, Release, and Deploy

on:
  # Trigger on pushes to the main branch and on new tags
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Grant permissions for GitHub token
permissions:
  contents: write # Needed to create releases, upload assets, and push tags
  pages: write
  id-token: write

# Concurrency settings to manage deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
      
        
  #============================================================================
  # JOB 1: Continuous Integration on push to the `main` branch
  # This job builds the kernel/extension based on changed files and creates tags.
  #============================================================================
  ci_build:
    name: CI Build & Auto-Tag
    # This job ONLY runs on pushes to the 'main' branch, not on tags.
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags.
          # This is CRITICAL for paths-filter to correctly compare changes.
          fetch-depth: 0
          
      - name: Install CMake
        uses: ssrobins/install-cmake@v1

      - name: Setup Pixi environment
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          cache: true

      - name: Check for changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          # Define the filters for different parts of the codebase.
          # The action will create a boolean output for each filter name.
          filters: |
            kernel:
              - 'src/**'
              - 'include/**'
              - 'CMakeLists.txt'
              - 'pixi.toml'
            extension:
              - 'extension/**'
            recipe:
              - 'recipe/recipe.yaml'

      - name: Build and install kernel (if source changed)
        # CORRECTED SYNTAX: Use the output directly as a boolean.
        if: steps.filter.outputs.kernel == 'true'
        run: pixi run -e kernel install

      - name: Install & Build JupyterLab extension (if source changed)
        # CORRECTED SYNTAX: Use the output directly as a boolean.
        if: steps.filter.outputs.extension == 'true'
        run: |
          pixi run -e default extension-setup
          pixi run -e default extension-build

      - name: Create Tag on Version Bump (if recipe changed)
        # CORRECTED SYNTAX: Use the output directly as a boolean.
        if: steps.filter.outputs.recipe == 'true'
        uses: mikefarah/yq@v4
        with:
          cmd: |
            VERSION=$(yq e '.context.version' 'recipe/recipe.yaml')
            TAG="v${VERSION}"
            echo "Version from recipe is ${VERSION}"
            
            # Check if the tag already exists to prevent errors
            if git rev-parse "${TAG}" >/dev/null 2>&1; then
              echo "Tag ${TAG} already exists. No new tag will be created."
            else
              echo "Tag ${TAG} does not exist. Creating and pushing new tag."
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git tag "${TAG}" -m "Release version ${VERSION}"
              git push origin "${TAG}"
            fi

    

  #============================================================================
  # JOB 2: Build, package, and create a release when a new tag is pushed
  #============================================================================
  release_and_deploy:
    name: Create Release and Deploy Pages
    # This job ONLY runs when a tag is pushed.
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi environment
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          cache: true

      - name: Build and install the xeus-ocaml kernel
        run: pixi run -e kernel install

      - name: Build the JupyterLite application
        run: pixi run -e default build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload JupyterLite artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: './_output'

      - name: Build conda package
        id: build-conda
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: recipe/recipe.yaml
          build-args: >-
            -c https://repo.prefix.dev/emscripten-forge-dev 
            -c conda-forge 
            --target-platform emscripten-wasm32

      - name: Create GitHub Release and Upload Conda Package
        uses: softprops/action-gh-release@v2
        with:
          # This action automatically uses the tag that triggered the workflow
          # and uploads the built conda package as an asset.
          files: ${{ steps.build-conda.outputs.pkg-path }}
          
  #============================================================================
  # JOB 3: Deploy the JupyterLite site to GitHub Pages
  #============================================================================
  deploy_pages:
    name: Deploy to GitHub Pages
    # This job only runs when a tag is pushed and after the release job is complete.
    if: startsWith(github.ref, 'refs/tags/')
    needs: release_and_deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy JupyterLite to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4