name: Release and Deploy

on:
  # This workflow ONLY runs when a tag is pushed.
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release_and_deploy:
    name: Create Release and Deploy Pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
  
      - name: Setup Pixi environment
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          cache: true

      - name: Build the JupyterLite application
        run: pixi run -e default build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload JupyterLite artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: './_output'

      - name: Build conda package
        id: build-conda
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: recipe/recipe.yaml
          build-args: >-
            -c https://repo.prefix.dev/emscripten-forge-dev 
            -c conda-forge 
            --target-platform emscripten-wasm32

      - name: Upload Conda Package to prefix.dev Channel
        run: |
          for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
            echo "Uploading ${pkg}"
            rattler-build upload prefix -c emscripten "${pkg}"
          done

      - name: Create GitHub Release and Upload Conda Package
        uses: softprops/action-gh-release@v2
        with:
              files: |
                output/*.conda
                output/*.tar.bz2
          
  deploy_pages:
    name: Deploy to GitHub Pages
    needs: release_and_deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy JupyterLite to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4